
= OPeNDAP AsciiDoc site
The most recent build of some of the OPeNDAP documentation.

== Quick Start 

The
 link:https://opendap.github.io/documentation/QuickStart.html[QuickStart Guide]
 link:https://opendap.github.io/documentation/QuickStart.pdf[(PDF)]
 provides a overview of our software and its use

== User Guide

The
link:https://opendap.github.io/documentation/UserGuideComprehensive.html[UserGuide]
link:https://opendap.github.io/documentation/UserGuideComprehensive.pdf[(PDF)]
provides general information about the OPeNDAP software, the two
versions of the Data Access Protocol (DAP) and information about
access to remote data made available using DAP.

== Data Access Tutorials
The link:https://opendap.github.io/documentation/tutorials/DataAccessTutorials.html[Data Access Tutorials]
show how to use various software clients to access data using the DAP web API.

== Hyrax Installation and Configuration Guide

The
link:https://opendap.github.io/hyrax_guide/Master_Hyrax_Guide.html[Hyrax Installation and Configuration Guide]
link:https://opendap.github.io/hyrax_guide/Master_Hyrax_Guide.pdf[(PDF)]
provides information about the Hyrax Data Server. In this guide you
will find a description of the server's featrues and all of its
configuration parameters. Also described in teh guide are other web
services that Hyrax provides, including WMS and WCS.

== Libdap library documentation
The link:https://opendap.github.io/libdap4/html/[libdap library documentation] provides reference information for our
implementation of DAP2 and DAP4.

== BES data server framework
The link:https://opendap.github.io/bes/html/[Back End Server (BES)] is the modular framework used to build the data
access and manipulation layer of the Hyrax data server.

== Notes about this repository

=== Building CommonMark from AsciiDoc

Quick note about coverting to CommonMark Markdown from AsciiDoc.

To convert to CM from adoc, use 'asciidoctor' and 'pandoc' like this:

    asciidoctor -b docbook5 -o quick_start_hack QuickStart.adoc
    pandoc -f docbook -t commonmark -o quick_start.cm quick_start_hack

=== About opendap.github.io

The https://opendap.github.io site is populated with HTML and PDF
documents that are automatically built any time an AsciiDoc file in
the documentation repo is updated on the master branch.

This page comes from the _github.com/OPeNDAP/documentation_
repository, but it contains links to other pages from other OPeNDAP
github documentation repositories (e.g., _hyrax\_guide_). To add new
documention from a new repo, first arrange to publish its content via
_gh-pages_ and _github.io_ and then link those pages here. See the
_github.com/OPeNDAP/hyrax_guide_ repo and the entry above for
_Master_Hyrax_Guide.html/pdf_ for an example.

=== Automaic github.io updates

See link:http://mgreau.com/posts/2016/03/28/asciidoc-to-gh-pages-with-travis-ci-docker-asciidoctor.html[Convert AsciiDoc to HTML/PDF & publish to GitHub Pages with Travis CI and Asciidoctor Docker containers] for the low-down on how the automatic updates work. 

Another take on the same sort of process - updating gh-pages from a .travis.yml file - that does not use asciidoctor: link:http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/[Automatically Update GitHub Pages with Travis].
