
= image:OPeNDAP-Logo-red.svg[width=350]  Documentation
:imagesdir: ./images
The most recent build of some of the OPeNDAP documentation.

== Quick Start 

The
 link:https://opendap.github.io/documentation/QuickStart.html[QuickStart Guide]
 link:https://opendap.github.io/documentation/QuickStart.pdf[(PDF)]
 provides a overview of our software and its use

== User Guide

The
link:https://opendap.github.io/documentation/UserGuideComprehensive.html[UserGuide]
link:https://opendap.github.io/documentation/UserGuideComprehensive.pdf[(PDF)]
provides general information about the OPeNDAP software, the two
versions of the Data Access Protocol (DAP) and information about
access to remote data made available using DAP.

== link:https://opendap.github.io/documentation/tutorials/DataAccessTutorials.html[Data Access Tutorials]
The link:https://opendap.github.io/documentation/tutorials/DataAccessTutorials.html[Data Access Tutorials]
show how to use various software clients to access data using the DAP web API.

== Client Authentication

Many institutions now require that you (or more accurately, your software client)
must authenticate before access to data will be permitted. This is notably true
for all NASA assets: Authentication is required for data access.

* link:https://opendap.github.io/documentation/tutorials/ClientAuthentication.html[
You can learn about DAP Client Software Authentication here.]

* link:https://opendap.github.io/documentation/tutorials/ClientAuthenticationWithEDLTokens.html[
You can learn about how to use NASA's EDL tokens for Client Software Authentication here.]


== Hyrax Installation and Configuration Guide

The
link:https://opendap.github.io/hyrax_guide/Master_Hyrax_Guide.html[Hyrax Installation and Configuration Guide]
link:https://opendap.github.io/hyrax_guide/Master_Hyrax_Guide.pdf[(PDF)]
provides information about the Hyrax Data Server. In this guide you
will find a description of the server's featrues and all of its
configuration parameters. Also described in teh guide are other web
services that Hyrax provides, including WMS and WCS.

== Libdap library documentation
The link:https://opendap.github.io/libdap4/html/[libdap library documentation] provides reference information for our
implementation of DAP2 and DAP4.

== BES data server framework
The link:https://opendap.github.io/bes/html/[Back End Server (BES)] is the modular framework used to build the data
access and manipulation layer of the Hyrax data server.

== Notes about this repository

=== How to build the documentation

The documentation is built by Travis CI with every PR which executs `asciidoctor`. Travis converts the `.adoc` source files to `.html` and then pushes these to GitHub Pages where the 
documentation is hosted.

When proposing changes to the documentation, we recommend first test these by building the documentation on your local computer. To do that, you will need `asciidoctor` installed
in your system.

Say you are proposing changes to the `QuickStart.adoc`. On your computer then run the following command:

```
asciidoctor QuickStart.adoc
```

You can now inspect the build on your local machine by running on your terminal `open QuickStart.html`, or simply by pasting `file://<file_path>/QuickStart.html` onto any browser
(`<file_path>` is the location of the `QuickStart.html` file on your filesystem. You can get this by running `pwd` in the same directory as your `QuickStart.html` file.)

=== About opendap.github.io/documentation/

The https://opendap.github.io/documentation/ site is populated with HTML and PDF
documents that are automatically built any time an AsciiDoc file in
the documentation repo is updated on the master branch.

This page comes from the _github.com/OPeNDAP/documentation_
repository, but it contains links to other pages from other OPeNDAP
github documentation repositories (e.g., _hyrax\_guide_). To add new
documention from a new repo, first arrange to publish its content via
_gh-pages_ and _github.io_ and then link those pages here. See the
_github.com/OPeNDAP/hyrax_guide_ repo and the entry above for
_Master_Hyrax_Guide.html/pdf_ for an example.

=== Automatic github.io updates

See
link:http://mgreau.com/posts/2016/03/28/asciidoc-to-gh-pages-with-travis-ci-docker-asciidoctor.html[Convert
AsciiDoc to HTML/PDF & publish to GitHub Pages with Travis CI and
Asciidoctor Docker containers] for the low-down on how the automatic
updates work. 

Another take on the same sort of process - updating gh-pages from a
.travis.yml file - that does not use asciidoctor:
link:http://www.steveklabnik.com/automatically_update_github_pages_with_travis_example/[Automatically
Update GitHub Pages with Travis].
