
= image:OPeNDAP-Logo-red.svg[width=350] Data Access Client Tutorials
:imagesdir: ../images
== Client Software Authentication
Some data providers, most notably NASA, require data access requests be
authenticated. This means you have to a user account with the institution and
any software client application working on your behalf (browser, cURL, etc)
must be provided with user credentials or tokens either through dynamic user
interaction or configuration.

* link:https://opendap.github.io/documentation/tutorials/ClientAuthentication.html[
You can learn about DAP Client Software Authentication here.]

* link:https://opendap.github.io/documentation/tutorials/ClientAuthenticationWithEDLTokens.html[
You can learn about how to use NASA's EDL tokens for Client Software Authentication here.]

== Command line clients
These clients are invoked from a shell and are typically used in an automated
data access activity, possibly written as a shell script.

*  link:https://opendap.github.io/documentation/tutorials/nccopy_tutorial.html[nccopy tutorial]

== Python client tutorials
Among the most stable and widely used within the Python ecosystem are NetCDF and https://pydap.github.io/pydap/intro.html[PyDAP]. Xarray, a widely popular package within the Pangeo ecosystem uses both as a backend `engine`, and both NetCDF and https://pydap.github.io/pydap/intro.html[PyDAP] are required dependencies for Xarray, which means installing Xarray installs NetCDF and https://pydap.github.io/pydap/intro.html[PyDAP] by default.  Between the two packages, we recommend getting started with https://pydap.github.io/pydap/intro.html[PyDAP] to best exploit OPeNDAP resources, because PyDAP has the following characteristics:

* Pure python implementation of the DAP protocol.
* Open-source, developed and maintained by the OPeNDAP team and the broad PyDAP/OPeNDAP community.
* Has its own lightweight server implementation.
* Server-side and data-proximmate subsetting. OPeNDAP servers are highly specialized to subset the original dataset. With https://pydap.github.io/pydap/intro.html[PyDAP], a user can add constraint expressions to the URL, a powerful tool once you get familiarize with.


Below are a combination of static and interactive resources. You can click the associated image image:badge_logo.svg[fit=line] Binder badge to run the notebooks in your browser.

* PyDAP's https://pydap.github.io/pydap/intro.html[documentation] - Inside you will find static tutorials, mostly with DAP4 protocol. Some of the example include working with Constraint Expressions.
	- https://pydap.github.io/pydap/en/notebooks/Authentication.html[Token-based Authentication] (necessary for example to access NASAEarth data).
	- Tutorial workflows for accesing and plotting various NASA and Non-NASA data product (https://pydap.github.io/pydap/en/notebooks/CMIP6.html[CMIP6], https://pydap.github.io/pydap/en/notebooks/ECCO.html[ECCOv4], https://pydap.github.io/pydap/en/notebooks/PACE.html[PACE] and https://pydap.github.io/pydap/en/notebooks/SWOT.html[SWOT]).

* link:https://github.com/OPENDAP/ESIP2024/tree/main[Interactive jupyter notebooks] image:badge_logo.svg[link=https://mybinder.org/v2/gh/OPENDAP/ESIP2024/main], showing similar workflows with PyDAP as that of its official documentation. The DAP2 example is that when working with https://pydap.github.io/pydap/en/notebooks/CMIP6.html[CMIP6] data.
	- *Requirements*: https://urs.earthdata.nasa.gov/home[EDL] account, and create a token for authentication.
	- *NOTE*: https://github.com/OPENDAP/ESIP2024/blob/main/binder/GetStarted.ipynb[GetStarted.ipynb] notebook should be executed first as it creates local file with https://urs.earthdata.nasa.gov/home[EDL] credentials needed to access data in the all other notebooks.


Older python resource:

*  link:https://github.com/OPENDAP/NASA-tutorials/blob/main/tutorials/colab/1.netcdf_tutorial.ipynb[NetCDF-python w/DAP4]
image:colab-badge.svg[fit=line, link="https://colab.research.google.com/github/OPENDAP/NASA-tutorials/blob/main/tutorials/colab/1.netcdf_tutorial.ipynb"] -
An iPython notebook tutorial for remote data access using NetCDF Python. When
NetCDF is used to access a remote dataset it does so by making DAP4 queries
to the remote service.

*  link:https://github.com/OPENDAP/NASA-tutorials/blob/main/tutorials/colab/2.xarray_netcdf_tutorial.ipynb[Xarray and netCDF4 w/DAP4]
image:colab-badge.svg[fit=line, link="https://colab.research.google.com/github/OPENDAP/NASA-tutorials/blob/main/tutorials/colab/2.xarray_netcdf_tutorial.ipynb"] -
An iPython notebook tutorial for remote data access using Xarray.


== Matlab
* link:https://opendap.github.io/documentation/tutorials/matlab_tutorial.html[Matlab Tutorial for remote data access] (beta).

== Tutorial Datasets
Several datasets are used in these tutorials and some general information about
each may be found on our
link:https://opendap.github.io/documentation/tutorials/TutorialDatasets.html[Tutorial Dataset Information]
page.

== _Coming Soon_
* DAP4 PyDAP Python sub-setting large datasets (notebook)
* Using the cURL command line to access data (shell)
* Panoply Tutorial for remote data access.


