
= OPeNDAP Data Access Client Tutorials

== Command line clients
These clients are invoked from a shell and are typically used in an automated
data access activity, possibly written as a shell script.

*  link:https://opendap.github.io/documentation/tutorials/nccopy_tutorial.html[nccopy tutorial]

== Python client tutorials
Python clients like PyDAp are best explained in a Jupyter (aka iPython) notebook.
You  can click the associated image:https://mybinder.org/badge_logo.svg[fit=line]
binder badge  to run the notebook in your browser.

* link:https://github.com/OPENDAP/notebooks/blob/master/tutorials/pydap_dap2_basic.ipynb[PyDAP w/DAP2]
image:https://mybinder.org/badge_logo.svg[fit=line, link="https://mybinder.org/v2/gh/OPENDAP/notebooks/master?labpath=tutorials%2Fpydap_dap2_basic.ipynb"] -
An iPython notebook tutorial for PyDAP with DAP2 access examples.


*  link:https://github.com/OPENDAP/notebooks/blob/master/tutorials/pydap_dap4_basic.ipynb[PyDAP w/DAP4]
image:https://mybinder.org/badge_logo.svg[fit=line, link="https://mybinder.org/v2/gh/OPENDAP/notebooks/master?labpath=tutorials%2Fpydap_dap4_basic.ipynb"] -
An iPython notebook tutorial for PyDAP with DAP4 data access examples

== Datasets
Several datasets are used in these tutorials and some general information about
each may be found on our
link:https://opendap.github.io/documentation/tutorials/TutorialDatasets.html[Tutorial Dataset Information]
information page.

== _Coming Soon_
* XArray Python tutorial (notebook)
* DAP2/4 NetCDF Python Tutorial (notebook)
* DAP4 PyDAP Python sub-setting large datasets (notebook)
* Using the cURL command line to access data (shell)
* Panoply Tutorial for remote data access.
* Matlab Tutorial for remote data access.
